export const colleges = [
  "University of Mumbai",
  "Pune University",
  "Anna University",
  "Delhi University",
  "Jadavpur University",
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "IIT Kharagpur",
  "NIT Trichy",
  "NIT Warangal",
  "BITS Pilani",
  "VIT University",
  "Manipal University",
  "Amity University",
  "Symbiosis International University",
  "Fergusson College",
  "St. Xavier's College",
  "Presidency University",
  "Loyola College Chennai",
  "Christ University",
  "Jain University",
  "SRM University",
  "Lovely Professional University",
  "Chandigarh University",
  "NMIMS Mumbai",
  "SP Jain Institute",
  "XLRI Jamshedpur",
];

export const departments = [
  "Computer Science",
  "Information Technology",
  "Electronics & Telecommunication",
  "Mechanical Engineering",
  "Civil Engineering",
  "Electrical Engineering",
  "BBA",
  "MBA",
  "BCom",
  "BA",
  "BSc",
  "BCA",
  "MCA",
  "MSc Computer Science",
];

export const bankData = [
  { name: "State Bank of India", ifscPrefix: "SBIN", shortCode: "sbi" },
  { name: "HDFC Bank", ifscPrefix: "HDFC", shortCode: "hdfc" },
  { name: "ICICI Bank", ifscPrefix: "ICIC", shortCode: "icici" },
  { name: "Axis Bank", ifscPrefix: "UTIB", shortCode: "axis" },
  { name: "Punjab National Bank", ifscPrefix: "PUNB", shortCode: "pnb" },
  { name: "Bank of Baroda", ifscPrefix: "BARB", shortCode: "bob" },
  { name: "Canara Bank", ifscPrefix: "CNRB", shortCode: "canara" },
  { name: "Kotak Mahindra Bank", ifscPrefix: "KKBK", shortCode: "kotak" },
  { name: "IndusInd Bank", ifscPrefix: "INDB", shortCode: "indusind" },
  { name: "Union Bank of India", ifscPrefix: "UBIN", shortCode: "ubi" },
  { name: "Bank of India", ifscPrefix: "BKID", shortCode: "boi" },
  { name: "Central Bank of India", ifscPrefix: "CBIN", shortCode: "cbi" },
];

export const upiHandles = [
  "@okicici",
  "@okhdfcbank",
  "@oksbi",
  "@okaxis",
  "@ybl",
  "@ibl",
  "@axl",
  "@upi",
  "@paytm",
  "@jupiteraxis",
];

export const products = [
  {
    name: "Bluetooth Earbuds",
    category: "Electronics",
    priceRange: [599, 4999],
  },
  {
    name: "Wireless Charger",
    category: "Electronics",
    priceRange: [399, 2499],
  },
  { name: "Smartwatch", category: "Electronics", priceRange: [1999, 19999] },
  { name: "Mobile Cover", category: "Accessories", priceRange: [99, 599] },
  { name: "USB-C Cable", category: "Accessories", priceRange: [149, 999] },
  { name: "Laptop Bag", category: "Bags", priceRange: [499, 2999] },
  { name: "Running Shoes", category: "Footwear", priceRange: [799, 5999] },
  { name: "Formal Shirt", category: "Clothing", priceRange: [499, 2499] },
  { name: "Kurta", category: "Clothing", priceRange: [399, 2999] },
  { name: "Denim Jeans", category: "Clothing", priceRange: [699, 3499] },
  { name: "Mixer Grinder", category: "Kitchen", priceRange: [1499, 7999] },
  { name: "Pressure Cooker", category: "Kitchen", priceRange: [599, 2999] },
  { name: "Air Fryer", category: "Kitchen", priceRange: [2499, 8999] },
  { name: "Novel (Hindi)", category: "Books", priceRange: [99, 499] },
  { name: "Study Guide", category: "Books", priceRange: [199, 799] },
  { name: "Yoga Mat", category: "Sports", priceRange: [299, 1999] },
  { name: "Cricket Bat", category: "Sports", priceRange: [499, 4999] },
  { name: "Face Wash", category: "Beauty", priceRange: [89, 499] },
  { name: "Hair Oil", category: "Beauty", priceRange: [79, 399] },
  { name: "Protein Powder", category: "Health", priceRange: [799, 3499] },
];

export const orderStatuses = [
  "Ordered",
  "Confirmed",
  "Packed",
  "Shipped",
  "Out for Delivery",
  "Delivered",
  "Cancelled",
  "Returned",
];
export const paymentMethods = [
  "UPI",
  "Credit Card",
  "Debit Card",
  "Net Banking",
  "Cash on Delivery",
  "EMI",
  "Wallet",
];
export const couriers = [
  "Blue Dart",
  "DTDC",
  "Delhivery",
  "Ekart",
  "Shadowfax",
  "Ecom Express",
  "Amazon Logistics",
  "Flipkart Logistics",
];

export const emailDomains = [
  "gmail.com",
  "yahoo.co.in",
  "outlook.com",
  "rediffmail.com",
  "hotmail.com",
];
